import {
  // template nav keys
  LayoutDashboard,
  Star,
  Mail,
  SquarePen,
  Calendar,
  MessageSquare,
  BarChart3,
  ClipboardList,
  Component,
  MousePointerClick,
  Table,
  Table2,
  Map,
  MapPin,
  Files,
  File,
  LogIn,
  UserPlus,
  // app concepts (used by navigation + pages in later phases)
  Home,
  CalendarClock,
  CalendarDays,
  Clock,
  Users,
  Contact,
  Settings,
  Bell,
  Building2,
  User,
  ShieldCheck,
  Briefcase,
  // utility / affordances
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  ArrowRight,
  ArrowLeft,
  Plus,
  Search,
  Download,
  Upload,
  Check,
  X,
  Menu,
  MoreHorizontal,
  Trash2,
  Pencil,
  Eye,
  LogOut,
  type LucideIcon,
} from 'lucide-react';

/**
 * Central icon registry. Maps semantic names to lucide components so the
 * sidebar, topbar, and pages all draw from one source (mirrors the inline-SVG
 * nav model in the Adminator template's 2026.js).
 */
export const ICONS = {
  // ── template nav keys ──
  dashboard: LayoutDashboard,
  pro: Star,
  email: Mail,
  compose: SquarePen,
  calendar: Calendar,
  chat: MessageSquare,
  charts: BarChart3,
  forms: ClipboardList,
  ui: Component,
  buttons: MousePointerClick,
  tables: Table,
  'basic-table': Table,
  datatable: Table2,
  maps: Map,
  'google-maps': MapPin,
  'vector-maps': Map,
  pages: Files,
  blank: File,
  signin: LogIn,
  signup: UserPlus,

  // ── app concepts ──
  home: Home,
  booking: CalendarClock,
  appointments: CalendarDays,
  schedule: CalendarDays,
  unavailability: CalendarClock,
  timesheet: Clock,
  employees: Users,
  contacts: Contact,
  settings: Settings,
  notifications: Bell,
  company: Building2,
  profile: User,
  admin: ShieldCheck,
  work: Briefcase,

  // ── affordances ──
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'arrow-right': ArrowRight,
  'arrow-left': ArrowLeft,
  plus: Plus,
  search: Search,
  download: Download,
  upload: Upload,
  check: Check,
  close: X,
  menu: Menu,
  more: MoreHorizontal,
  delete: Trash2,
  edit: Pencil,
  view: Eye,
  logout: LogOut,
  bell: Bell,
  user: User,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;
