import { Access, BrachCategory, RoutePlaceMent, type RouteBranch } from '../route-types';

export const AUTH_ROUTES: RouteBranch[] = [
  {
      id: 'auth',
      href: '/auth',
      label: 'Autentisering',
      category: BrachCategory.AUTH,
      accessType: Access.PUBLIC,
      hidden: true,
      iconName: 'Key',
      children: [
        {
          id: 'auth.sign-in',
          href: '/auth/sign-in',
          label: 'Logg inn',
          category: BrachCategory.AUTH,
          placement: RoutePlaceMent.NAVIGATION,
          accessType: Access.NOT_AUTHENTICATED,
          iconName: 'LogIn',
          excludeLayout: true,
        },
        {
          id: 'auth.sign-up',
          href: '/auth/sign-up',
          label: 'Opprett konto',
          category: BrachCategory.AUTH,
          accessType: Access.NOT_AUTHENTICATED,
          iconName: 'UserPlus',
        },
        {
          id: 'auth.check-email',
          href: '/auth/check-email',
          label: 'Sjekk e-post',
          category: BrachCategory.AUTH,
          accessType: Access.NOT_AUTHENTICATED,
          hidden: true,
        },
        {
          id: 'auth.collect-email',
          href: '/auth/collect-email',
          label: 'Legg til e-post',
          category: BrachCategory.AUTH,
          accessType: Access.NOT_AUTHENTICATED,
          hidden: true,
        },
        {
          id: 'auth.collect-mobile',
          href: '/auth/collect-mobile',
          label: 'Legg til mobil',
          category: BrachCategory.AUTH,
          accessType: Access.NOT_AUTHENTICATED,
          hidden: true,
        },
        {
          id: 'auth.forgot-password',
          href: '/auth/forgot-password',
          label: 'Glemt passord',
          category: BrachCategory.AUTH,
          accessType: Access.NOT_AUTHENTICATED,
          iconName: 'Key',
        },
        {
          id: 'auth.reset-password',
          href: '/auth/reset-password',
          label: 'Tilbakestill passord',
          category: BrachCategory.AUTH,
          accessType: Access.NOT_AUTHENTICATED,
          iconName: 'Key',
        },
        {
          id: 'auth.verify-email',
          href: '/auth/verify-email',
          label: 'Bekreft e-post',
          category: BrachCategory.AUTH,
          accessType: Access.NOT_AUTHENTICATED,
          hidden: true,
        },
        {
          id: 'auth.verify-mobile',
          href: '/auth/verify-mobile',
          label: 'Bekreft mobil',
          category: BrachCategory.AUTH,
          accessType: Access.NOT_AUTHENTICATED,
          hidden: true,
        },
        {
          id: 'auth.respond-invite',
          href: '/auth/respond-invite',
          label: 'Aksepter invitasjon',
          category: BrachCategory.NONE,
          accessType: Access.NOT_AUTHENTICATED,
          iconName: 'UserPlus',
        },
        {
          id: 'auth.respond-user-invite',
          href: '/auth/respond-user-invite',
          label: 'Aksepter brukerinvitasjon',
          category: BrachCategory.NONE,
          accessType: Access.NOT_AUTHENTICATED,
          iconName: 'UserPlus',
        },
        {
          id: 'auth.sign-out',
          href: '/auth/sign-out',
          label: 'Logg ut',
          category: BrachCategory.AUTH,
          placement: RoutePlaceMent.NAVIGATION,
          accessType: Access.AUTHENTICATED,
          iconName: 'LogOut',
        },
      ],
    }
];
