import { Access, BrachCategory, CompanyRole, RoutePlaceMent, type RouteBranch } from '../route-types';

export const COMPANY_ROUTES: RouteBranch[] = [
  {
    id: 'company',
    href: '/company',
    label: 'Mitt selskap',
    category: BrachCategory.COMPANY,
    placement: RoutePlaceMent.SIDEBAR,
    accessType: Access.ROLE,
    companyRoles: [CompanyRole.ADMIN, CompanyRole.EMPLOYEE],
    iconName: 'Building2',
    children: [
      {
        id: 'company.request-role-delete',
        href: '/company/request-role-delete',
        label: 'Etterspørsel om å slette rolle',
        category: BrachCategory.NONE,
        hidden: true,
        accessType: Access.ROLE,
        companyRoles: [CompanyRole.ADMIN],
      },
      {
        id: 'company.admin',
        href: '/company/admin',
        label: 'Administrasjon',
        category: BrachCategory.NONE,
        accessType: Access.ROLE,
        companyRoles: [CompanyRole.ADMIN],
        iconName: 'Settings',
        children: [
          {
            id: 'company.admin.settings',
            href: '/company/admin/settings',
            label: 'Innstillinger',
            category: BrachCategory.COMPANY,
            accessType: Access.ROLE,
            companyRoles: [CompanyRole.ADMIN],
            iconName: 'Settings',
          },
          {
            id: 'company.admin.employees',
            href: '/company/admin/employees',
            label: 'Ansatte',
            category: BrachCategory.COMPANY,
            accessType: Access.ROLE,
            companyRoles: [CompanyRole.ADMIN],
            iconName: 'Users',
            children: [
              {
                id: 'company.admin.employees.invite',
                href: '/company/admin/employees/invite',
                label: 'Inviter ansatt',
                category: BrachCategory.COMPANY,
                accessType: Access.ROLE,
                companyRoles: [CompanyRole.ADMIN],
                hidden: true,
              },
              {
                id: 'company.admin.employees.edit',
                href: '/company/admin/employees/edit',
                label: 'Rediger ansatt',
                category: BrachCategory.COMPANY,
                accessType: Access.ROLE,
                companyRoles: [CompanyRole.ADMIN],
                hidden: true,
              },
            ],
          },
          {
            id: 'company.admin.contacts',
            href: '/company/admin/contacts',
            label: 'Kontakter',
            category: BrachCategory.COMPANY,
            accessType: Access.ROLE,
            companyRoles: [CompanyRole.ADMIN, CompanyRole.EMPLOYEE],
            iconName: 'Users',
            children: [
              {
                id: 'company.admin.contacts.create',
                href: '/company/admin/contacts/create',
                label: 'Opprett kontakt',
                category: BrachCategory.COMPANY,
                accessType: Access.ROLE,
                companyRoles: [CompanyRole.ADMIN, CompanyRole.EMPLOYEE],
                hidden: true,
              },
              {
                id: 'company.admin.contacts.edit',
                href: '/company/admin/contacts/edit',
                label: 'Rediger kontakt',
                category: BrachCategory.COMPANY,
                accessType: Access.ROLE,
                companyRoles: [CompanyRole.ADMIN, CompanyRole.EMPLOYEE],
                hidden: true,
              },
            ],
          },
        ],
      },
      {
        id: 'company.booking',
        href: '/company/booking',
        label: 'Booking',
        category: BrachCategory.COMPANY,
        placement: RoutePlaceMent.SIDEBAR,
        accessType: Access.PRODUCT,
        companyRoles: [CompanyRole.ADMIN, CompanyRole.EMPLOYEE],
        iconName: 'Calendar',
        children: [
          {
            id: 'company.booking.admin',
            href: '/company/booking/admin',
            label: 'Administrasjon',
            category: BrachCategory.COMPANY,
            accessType: Access.PRODUCT,
            companyRoles: [CompanyRole.ADMIN],
            iconName: 'Settings',
            children: [
              {
                id: 'company.booking.admin.settings',
                href: '/company/booking/admin/settings',
                label: 'Instillinger',
                hidden: true,
                category: BrachCategory.COMPANY,
                accessType: Access.PRODUCT,
                companyRoles: [CompanyRole.ADMIN],
                iconName: 'Settings',
              },
              {
                id: 'company.booking.admin.services',
                href: '/company/booking/admin/services',
                label: 'Tjenester',
                category: BrachCategory.COMPANY,
                accessType: Access.PRODUCT,
                companyRoles: [CompanyRole.ADMIN],
                iconName: 'Briefcase',
                children: [
                  {
                    id: 'company.booking.admin.services.create',
                    href: '/company/booking/admin/services/create',
                    label: 'Opprett tjeneste',
                    category: BrachCategory.COMPANY,
                    accessType: Access.PRODUCT,
                    companyRoles: [CompanyRole.ADMIN],
                    hidden: true,
                  },
                  {
                    id: 'company.booking.admin.services.edit',
                    href: '/company/booking/admin/services/edit',
                    label: 'Rediger tjeneste',
                    category: BrachCategory.COMPANY,
                    accessType: Access.PRODUCT,
                    companyRoles: [CompanyRole.ADMIN],
                    hidden: true,
                  },
                ],
              },
              {
                id: 'company.booking.admin.service-groups',
                href: '/company/booking/admin/service-groups',
                label: 'Tjeneste grupper',
                category: BrachCategory.COMPANY,
                accessType: Access.PRODUCT,
                companyRoles: [CompanyRole.ADMIN],
                iconName: 'FolderKanban',
                children: [
                  {
                    id: 'company.booking.admin.service-groups.services',
                    href: '/company/booking/admin/service-groups/services',
                    label: 'Tjenester',
                    category: BrachCategory.COMPANY,
                    accessType: Access.PRODUCT,
                    companyRoles: [CompanyRole.ADMIN],
                    iconName: 'Briefcase',
                    hidden: true,
                    children: [
                      {
                        id: 'company.booking.admin.service-groups.services.create',
                        href: '/company/booking/admin/service-groups/services/create',
                        label: 'Opprett tjeneste',
                        category: BrachCategory.COMPANY,
                        accessType: Access.PRODUCT,
                        companyRoles: [CompanyRole.ADMIN],
                        hidden: true,
                      },
                      {
                        id: 'company.booking.admin.service-groups.services.edit',
                        href: '/company/booking/admin/service-groups/services/edit',
                        label: 'Rediger tjeneste',
                        category: BrachCategory.COMPANY,
                        accessType: Access.PRODUCT,
                        companyRoles: [CompanyRole.ADMIN],
                        hidden: true,
                      },
                    ],
                  },
                  {
                    id: 'company.booking.admin.service-groups.create',
                    href: '/company/booking/admin/service-groups/create',
                    label: 'Opprett tjenestegruppe',
                    category: BrachCategory.COMPANY,
                    accessType: Access.PRODUCT,
                    companyRoles: [CompanyRole.ADMIN],
                    hidden: true,
                  },
                  {
                    id: 'company.booking.admin.service-groups.edit',
                    href: '/company/booking/admin/service-groups/edit',
                    label: 'Rediger tjenestegruppe',
                    category: BrachCategory.COMPANY,
                    accessType: Access.PRODUCT,
                    companyRoles: [CompanyRole.ADMIN],
                    hidden: true,
                  },
                ],
              },
            ],
          },
          {
            id: 'company.booking.profile',
            href: '/company/booking/profile',
            label: 'Min booking profil',
            category: BrachCategory.COMPANY,
            accessType: Access.PRODUCT,
            companyRoles: [CompanyRole.ADMIN, CompanyRole.EMPLOYEE],
            iconName: 'UserCircle',
            children: [
              {
                id: 'company.booking.profile.create',
                href: '/company/booking/profile/create',
                label: 'Opprett booking profil',
                category: BrachCategory.COMPANY,
                accessType: Access.PRODUCT,
                companyRoles: [CompanyRole.ADMIN, CompanyRole.EMPLOYEE],
                hidden: true,
              },
              {
                id: 'company.booking.profile.edit',
                href: '/company/booking/profile/edit',
                label: 'Rediger booking profil',
                category: BrachCategory.COMPANY,
                accessType: Access.PRODUCT,
                companyRoles: [CompanyRole.ADMIN, CompanyRole.EMPLOYEE],
                hidden: true,
              },
            ],
          },
          {
            id: 'company.booking.schedule-unavailability',
            href: '/company/booking/schedule-unavailability',
            label: 'Mitt ferie avik',
            category: BrachCategory.COMPANY,
            accessType: Access.PRODUCT,
            companyRoles: [CompanyRole.ADMIN, CompanyRole.EMPLOYEE],
            iconName: 'CalendarX2',
            children: [
              {
                id: 'company.booking.schedule-unavailability.create',
                href: '/company/booking/schedule-unavailability/create',
                label: 'Legg til fravær',
                category: BrachCategory.COMPANY,
                accessType: Access.PRODUCT,
                companyRoles: [CompanyRole.ADMIN, CompanyRole.EMPLOYEE],
                hidden: true,
              },
            ],
          },
          {
            id: 'company.booking.appointments',
            href: '/company/booking/appointments',
            label: 'Time bestillinger',
            category: BrachCategory.COMPANY,
            accessType: Access.PRODUCT,
            companyRoles: [CompanyRole.ADMIN, CompanyRole.EMPLOYEE],
            iconName: 'ClipboardList',
            children: [
              {
                id: 'company.booking.appointments.detail',
                href: '/company/booking/appointments/:appointmentId',
                label: 'Timebestilling',
                category: BrachCategory.COMPANY,
                accessType: Access.PRODUCT,
                companyRoles: [CompanyRole.ADMIN, CompanyRole.EMPLOYEE],
                hidden: true,
                excludeLayout: true,
              },
              {
                id: 'company.booking.appointments.create',
                href: '/company/booking/appointments/create',
                label: 'Bestill ny time',
                category: BrachCategory.COMPANY,
                accessType: Access.PRODUCT,
                companyRoles: [CompanyRole.ADMIN, CompanyRole.EMPLOYEE],
                iconName: 'Calendar',
                hidden: true,
              },
              {
                id: 'company.booking.appointments.upload-image',
                href: '/company/booking/appointments/upload-image',
                label: 'Last opp bilde',
                category: BrachCategory.COMPANY,
                accessType: Access.PRODUCT,
                companyRoles: [CompanyRole.ADMIN, CompanyRole.EMPLOYEE],
                hidden: true,
              },
            ],
          },
          {
            id: 'company.booking.schedule',
            href: '/company/booking/schedule',
            label: 'Kalenderoversikt',
            category: BrachCategory.COMPANY,
            accessType: Access.PRODUCT,
            companyRoles: [CompanyRole.ADMIN, CompanyRole.EMPLOYEE],
            iconName: 'Clock',
            children: [
              {
                id: 'company.booking.schedule.availabilities',
                href: '/company/booking/schedule/availabilities',
                label: 'Tilgjengeligheter',
                category: BrachCategory.COMPANY,
                accessType: Access.PRODUCT,
                companyRoles: [CompanyRole.ADMIN, CompanyRole.EMPLOYEE],
                hidden: true,
              },
              {
                id: 'company.booking.schedule.availabilities.edit',
                href: '/company/booking/schedule/availabilities/edit',
                label: 'Rediger tilgjengelighet',
                category: BrachCategory.COMPANY,
                accessType: Access.PRODUCT,
                companyRoles: [CompanyRole.ADMIN, CompanyRole.EMPLOYEE],
                hidden: true,
              },
            ],
          },
        ],
      },
      {
        id: 'company.offer',
        href: '/company/offers',
        label: 'Tilbud',
        category: BrachCategory.COMPANY,
        placement: RoutePlaceMent.SIDEBAR,
        accessType: Access.PRODUCT,
        companyRoles: [CompanyRole.ADMIN, CompanyRole.EMPLOYEE],
        iconName: 'FileText',
        children: [
          {
            id: 'company.offer.create',
            href: '/company/offers/create',
            label: 'Nytt tilbud',
            category: BrachCategory.COMPANY,
            accessType: Access.PRODUCT,
            companyRoles: [CompanyRole.ADMIN, CompanyRole.EMPLOYEE],
            hidden: true,
          },
          {
            id: 'company.offer.detail',
            href: '/company/offers/:offerId',
            label: 'Tilbudsdetaljer',
            category: BrachCategory.COMPANY,
            accessType: Access.PRODUCT,
            companyRoles: [CompanyRole.ADMIN, CompanyRole.EMPLOYEE],
            hidden: true,
          },
          {
            id: 'company.offer.catalog',
            href: '/company/offers/catalog',
            label: 'Varekatalog',
            category: BrachCategory.COMPANY,
            accessType: Access.PRODUCT,
            companyRoles: [CompanyRole.ADMIN, CompanyRole.EMPLOYEE],
            iconName: 'Briefcase',
          },
        ],
      },
      {
        id: 'company.notifications',
        href: '/company/notifications',
        label: 'Varsler',
        category: BrachCategory.COMPANY,
        placement: RoutePlaceMent.SIDEBAR,
        accessType: Access.ROLE,
        companyRoles: [CompanyRole.ADMIN, CompanyRole.EMPLOYEE],
        iconName: 'Bell',
        children: [
          {
            id: 'company.notifications.view',
            href: '/company/notifications/:id',
            label: 'Vis varsel',
            category: BrachCategory.COMPANY,
            accessType: Access.ROLE,
            placement: RoutePlaceMent.SIDEBAR,
            companyRoles: [CompanyRole.ADMIN, CompanyRole.EMPLOYEE],
            hidden: true,
          },
        ],
      },
      {
        id: 'company.timesheet',
        href: '/company/timesheets',
        label: 'Timelister',
        category: BrachCategory.COMPANY,
        placement: RoutePlaceMent.SIDEBAR,
        accessType: Access.PRODUCT,
        companyRoles: [CompanyRole.ADMIN, CompanyRole.EMPLOYEE],
        iconName: 'Clock',
        children: [
          {
            id: 'company.timesheet.admin',
            href: '/company/timesheets/admin',
            label: 'Administrasjon',
            category: BrachCategory.COMPANY,
            accessType: Access.PRODUCT,
            placement: RoutePlaceMent.SIDEBAR,
            companyRoles: [CompanyRole.ADMIN],
            children: [
              {
                id: 'company.timesheet.admin.submissions',
                href: '/company/timesheets/admin/submissions',
                label: 'Innsendinger',
                category: BrachCategory.COMPANY,
                accessType: Access.PRODUCT,
                placement: RoutePlaceMent.SIDEBAR,
                companyRoles: [CompanyRole.ADMIN],
              },
            ],
          },
          {
            id: 'company.timesheet.register',
            href: '/company/timesheets/register',
            label: 'Registrer timer',
            category: BrachCategory.COMPANY,
            accessType: Access.PRODUCT,
            placement: RoutePlaceMent.SIDEBAR,
            companyRoles: [CompanyRole.ADMIN, CompanyRole.EMPLOYEE],
          },
          {
            id: 'company.timesheet.edit-range',
            href: '/company/timesheets/range/:id',
            label: 'Rediger tidsintervall',
            category: BrachCategory.COMPANY,
            accessType: Access.PRODUCT,
            placement: RoutePlaceMent.SIDEBAR,
            companyRoles: [CompanyRole.ADMIN, CompanyRole.EMPLOYEE],
            hidden: true,
          },
          {
            id: 'company.timesheet.edit-hours',
            href: '/company/timesheets/hours/:id',
            label: 'Rediger timerregistrering',
            category: BrachCategory.COMPANY,
            accessType: Access.PRODUCT,
            placement: RoutePlaceMent.SIDEBAR,
            companyRoles: [CompanyRole.ADMIN, CompanyRole.EMPLOYEE],
            hidden: true,
          },
        ],
      },
    ],
  },
];
