import { Access, BrachCategory, RoutePlaceMent, type RouteBranch } from '../route-types';

export const BOOKING_ROUTES: RouteBranch[] = [
  {
    id: 'booking',
    href: '/booking',
    label: 'BiT Booking',
    category: BrachCategory.PUBLIC,
    accessType: Access.PUBLIC,
    iconName: 'Calendar',
    children: [
      {
        id: 'booking.public',
        href: '/booking/public',
        label: 'Bestill time',
        category: BrachCategory.PUBLIC,
        accessType: Access.PUBLIC,
        iconName: 'Calendar',
        children: [
          {
            id: 'booking.public.appointment',
            href: '/booking/public/appointment',
            category: BrachCategory.PUBLIC,
            accessType: Access.PUBLIC,
            children: [
              {
                id: 'booking.public.appointment.session',
                href: '/booking/public/appointment/session',
                category: BrachCategory.PUBLIC,
                accessType: Access.PUBLIC,
                children: [
                  {
                    id: 'booking.public.appointment.session.contact',
                    href: '/booking/public/appointment/session/contact',
                    label: 'Bruker',
                    category: BrachCategory.NONE,
                    accessType: Access.PUBLIC,
                    hidden: true,
                    iconName: 'Users',
                    children: [
                      {
                        id: 'booking.public.appointment.session.contact.sign-in',
                        href: '/booking/public/appointment/session/contact/sign-in',
                        category: BrachCategory.NONE,
                        accessType: Access.PUBLIC,
                        excludeLayout: true,
                      },
                      {
                        id: 'booking.public.appointment.session.contact.sign-up',
                        href: '/booking/public/appointment/session/contact/sign-up',
                        category: BrachCategory.NONE,
                        accessType: Access.PUBLIC,
                        excludeLayout: true,
                      },
                      {
                        id: 'booking.public.appointment.session.contact.verify-email',
                        href: '/booking/public/appointment/session/contact/verify-email',
                        category: BrachCategory.NONE,
                        accessType: Access.PUBLIC,
                        excludeLayout: true,
                      },
                      {
                        id: 'booking.public.appointment.session.contact.verify-mobile',
                        href: '/booking/public/appointment/session/contact/verify-mobile',
                        category: BrachCategory.NONE,
                        accessType: Access.PUBLIC,
                        excludeLayout: true,
                      },
                      {
                        id: 'booking.public.appointment.session.contact.collect-email',
                        href: '/booking/public/appointment/session/contact/collect-email',
                        category: BrachCategory.NONE,
                        accessType: Access.PUBLIC,
                        excludeLayout: true,
                      },
                      {
                        id: 'booking.public.appointment.session.contact.collect-mobile',
                        href: '/booking/public/appointment/session/contact/collect-mobile',
                        category: BrachCategory.NONE,
                        accessType: Access.PUBLIC,
                        excludeLayout: true,
                      },
                    ],
                  },
                  {
                    id: 'booking.public.appointment.session.employee',
                    href: '/booking/public/appointment/session/employee',
                    label: 'Velg behandler',
                    category: BrachCategory.NONE,
                    accessType: Access.PUBLIC,
                    hidden: true,
                    iconName: 'UserCircle',
                  },
                  {
                    id: 'booking.public.appointment.session.select-services',
                    href: '/booking/public/appointment/session/select-services',
                    label: 'Velg tjenester',
                    category: BrachCategory.NONE,
                    accessType: Access.PUBLIC,
                    hidden: true,
                    iconName: 'Briefcase',
                  },
                  {
                    id: 'booking.public.appointment.session.select-time',
                    href: '/booking/public/appointment/session/select-time',
                    label: 'Velg tidspunkt',
                    category: BrachCategory.NONE,
                    accessType: Access.PUBLIC,
                    hidden: true,
                    iconName: 'Clock',
                  },
                  {
                    id: 'booking.public.appointment.session.overview',
                    href: '/booking/public/appointment/session/overview',
                    label: 'Oversikt',
                    category: BrachCategory.NONE,
                    accessType: Access.PUBLIC,
                    hidden: true,
                    iconName: 'ClipboardList',
                  },
                ],
              },
              {
                id: 'booking.public.appointment.success',
                href: '/booking/public/appointment/success',
                category: BrachCategory.NONE,
                accessType: Access.PUBLIC,
                hidden: true,
              },
              {
                id: 'booking.public.appointment.cancel',
                href: '/booking/public/appointment/cancel',
                category: BrachCategory.NONE,
                accessType: Access.PUBLIC,
                hidden: true,
              },
              {
                id: 'booking.public.appointment.cancel-by-id',
                href: '/booking/public/appointment/cancel-by-id/:appointmentId',
                category: BrachCategory.NONE,
                accessType: Access.AUTHENTICATED,
                hidden: true,
              },
            ],
          },
          {
            id: 'booking.public.my-appointments',
            href: '/booking/public/my-appointments',
            label: 'Mine bookinger',
            category: BrachCategory.USER,
            placement: RoutePlaceMent.NAVIGATION,
            accessType: Access.AUTHENTICATED,
          },
        ],
      },
    ],
  },
];
