import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

type ServiceAliasConfig = {
  service: 'base' | 'booking' | 'notification' | 'timesheet';
  runtimeExport: 'Base' | 'Booking' | 'Notification' | 'Timesheet';
  runtimeLocal: string;
  aliases: string[];
};

const configs: ServiceAliasConfig[] = [
  {
    service: 'base',
    runtimeExport: 'Base',
    runtimeLocal: 'BaseSdk',
    aliases: [
      'Actuator',
      'AuthController',
      'AdminCompanyController',
      'AdminCompanyUserController',
      'CompanyUserController',
      'CompanyUserContactController',
      'PublicCompanyController',
      'PublicUserController',
      'RootController',
    ],
  },
  {
    service: 'booking',
    runtimeExport: 'Booking',
    runtimeLocal: 'BookingSdk',
    aliases: [
      'Actuator',
      'AppointmentsController',
      'CompanyUserAppointmentController',
      'CompanyUserBookingController',
      'CompanyUserBookingProfileController',
      'CompanyUserScheduleController',
      'CompanyUserScheduleUnavailabilityController',
      'CompanyUserServiceGroupController',
      'DailyScheduleController',
      'PublicAppointmentSessionController',
      'RootController',
      'ServiceController',
    ],
  },
  {
    service: 'notification',
    runtimeExport: 'Notification',
    runtimeLocal: 'NotificationSdk',
    aliases: ['CompanyUserInAppNotificationController'],
  },
  {
    service: 'timesheet',
    runtimeExport: 'Timesheet',
    runtimeLocal: 'TimesheetSdk',
    aliases: ['AdminTimeSheetEntryController', 'CompanyUserTimesheetEntryController'],
  },
];

const START = '// compat-aliases:start';
const END = '// compat-aliases:end';

function upsertAliases(config: ServiceAliasConfig) {
  const file = resolve(process.cwd(), `app/api/generated/${config.service}/index.ts`);
  let source = readFileSync(file, 'utf8');

  const importLine = `import { ${config.runtimeExport} as ${config.runtimeLocal} } from './sdk.gen';`;
  if (!source.includes(importLine)) {
    source = source.replace(
      `// This file is auto-generated by @hey-api/openapi-ts\n\n`,
      `// This file is auto-generated by @hey-api/openapi-ts\n\n${importLine}\n`,
    );
  }

  for (const alias of config.aliases) {
    const duplicateAliasRegex = new RegExp(`^export const ${alias} = [^;]+;\\n?`, 'gm');
    source = source.replace(duplicateAliasRegex, '');
  }

  const aliasLines = config.aliases.map((name) => `export const ${name} = ${config.runtimeLocal};`);
  const block = `${START}\n${aliasLines.join('\n')}\n${END}`;

  if (source.includes(START) && source.includes(END)) {
    const start = source.indexOf(START);
    const end = source.indexOf(END) + END.length;
    const updated = `${source.slice(0, start)}${block}${source.slice(end)}`;
    writeFileSync(file, updated, 'utf8');
    return;
  }

  const lines = source.split('\n');
  const exportLineIndex = lines.findIndex(
    (line) => line.startsWith('export {') && line.includes(config.runtimeExport) && line.includes("from './sdk.gen';"),
  );
  if (exportLineIndex === -1) {
    throw new Error(`Could not find runtime export line for ${config.service}`);
  }

  const insertAt = lines.slice(0, exportLineIndex + 1).join('\n').length + 1;
  const updated = `${source.slice(0, insertAt)}${block}\n${source.slice(insertAt)}`;
  writeFileSync(file, updated, 'utf8');
}

for (const config of configs) {
  upsertAliases(config);
}

console.log('Applied generated API controller compatibility aliases.');
