// Common Responses
import type { ApiResponse } from './generic-wrapper';
import type { AppointmentDto, AuthenticatedUserPayload, AuthenticationTokenDto, CompanyBookingInfoDto, CompanySummaryDto, CompanyUserDto, CompanyUserProfileDto, ContactDto, DailyScheduleDto, ImageDto, InvitedUserTokenDto, JwtClaims, PaginatedResponseAppointmentDto, PaginatedResponseCompanyUserDto, PaginatedResponseContactDto, PaginatedResponseServiceDto, PaginatedResponseServiceGroupDto, PublicCompanyUserDto, ScheduleDto, ServiceDto, ServiceGroupDto } from './models';

export type ApiResponseAppointmentDto = ApiResponse<AppointmentDto>;
export type ApiResponseAuthenticatedUserPayload = ApiResponse<AuthenticatedUserPayload>;
export type ApiResponseAuthenticationTokenDto = ApiResponse<AuthenticationTokenDto>;
export type ApiResponseBoolean = ApiResponse<Boolean>;
export type ApiResponseCompanyBookingInfoDto = ApiResponse<CompanyBookingInfoDto>;
export type ApiResponseCompanySummaryDto = ApiResponse<CompanySummaryDto>;
export type ApiResponseCompanyUserDto = ApiResponse<CompanyUserDto>;
export type ApiResponseCompanyUserProfileDto = ApiResponse<CompanyUserProfileDto>;
export type ApiResponseContactDto = ApiResponse<ContactDto>;
export type ApiResponseImageDto = ApiResponse<ImageDto>;
export type ApiResponseInvitedUserTokenDto = ApiResponse<InvitedUserTokenDto>;
export type ApiResponseJwtClaims = ApiResponse<JwtClaims>;
export type ApiResponseListAppointmentDto = ApiResponse<AppointmentDto[]>;
export type ApiResponseListCompanySummaryDto = ApiResponse<CompanySummaryDto[]>;
export type ApiResponseListContactDto = ApiResponse<ContactDto[]>;
export type ApiResponseListDailyScheduleDto = ApiResponse<DailyScheduleDto[]>;
export type ApiResponseListImageDto = ApiResponse<ImageDto[]>;
export type ApiResponseListPublicCompanyUserDto = ApiResponse<PublicCompanyUserDto[]>;
export type ApiResponsePaginatedResponseAppointmentDto = ApiResponse<PaginatedResponseAppointmentDto>;
export type ApiResponsePaginatedResponseCompanyUserDto = ApiResponse<PaginatedResponseCompanyUserDto>;
export type ApiResponsePaginatedResponseContactDto = ApiResponse<PaginatedResponseContactDto>;
export type ApiResponsePaginatedResponseServiceDto = ApiResponse<PaginatedResponseServiceDto>;
export type ApiResponsePaginatedResponseServiceGroupDto = ApiResponse<PaginatedResponseServiceGroupDto>;
export type ApiResponseScheduleDto = ApiResponse<ScheduleDto>;
export type ApiResponseServiceDto = ApiResponse<ServiceDto>;
export type ApiResponseServiceGroupDto = ApiResponse<ServiceGroupDto>;
export type ApiResponseUnit = ApiResponse<void>;
