// Common Responses
import type { ApiResponse } from './generic-wrapper';
import type { AppointmentDto, AppointmentSessionDto, AppointmentSessionOverviewDto, AuthenticatedUserPayload, AuthenticationTokenDto, BookingProfileDto, CompanySummaryDto, CompanyUserDto, ContactDto, DailyScheduleDto, GroupedServiceGroupsDto, ImageDto, InvitedUserTokenDto, JwtClaims, PaginatedResponseAppointmentDto, PaginatedResponseCompanyUserDto, PaginatedResponseContactDto, PaginatedResponseServiceDto, PaginatedResponseServiceGroupDto, PublicCompanyUserDto, ScheduleDto, ServiceDto, ServiceGroupDto, UserDto } from './models';

export type ApiResponseAppointmentDto = ApiResponse<AppointmentDto>;
export type ApiResponseAppointmentSessionDto = ApiResponse<AppointmentSessionDto>;
export type ApiResponseAppointmentSessionOverviewDto = ApiResponse<AppointmentSessionOverviewDto>;
export type ApiResponseAuthenticatedUserPayload = ApiResponse<AuthenticatedUserPayload>;
export type ApiResponseAuthenticationTokenDto = ApiResponse<AuthenticationTokenDto>;
export type ApiResponseBookingProfileDto = ApiResponse<BookingProfileDto>;
export type ApiResponseBoolean = ApiResponse<Boolean>;
export type ApiResponseCompanySummaryDto = ApiResponse<CompanySummaryDto>;
export type ApiResponseCompanyUserDto = ApiResponse<CompanyUserDto>;
export type ApiResponseContactDto = ApiResponse<ContactDto>;
export type ApiResponseImageDto = ApiResponse<ImageDto>;
export type ApiResponseInvitedUserTokenDto = ApiResponse<InvitedUserTokenDto>;
export type ApiResponseJwtClaims = ApiResponse<JwtClaims>;
export type ApiResponseListBookingProfileDto = ApiResponse<BookingProfileDto[]>;
export type ApiResponseListCompanySummaryDto = ApiResponse<CompanySummaryDto[]>;
export type ApiResponseListContactDto = ApiResponse<ContactDto[]>;
export type ApiResponseListDailyScheduleDto = ApiResponse<DailyScheduleDto[]>;
export type ApiResponseListGroupedServiceGroupsDto = ApiResponse<GroupedServiceGroupsDto[]>;
export type ApiResponseListImageDto = ApiResponse<ImageDto[]>;
export type ApiResponseListPublicCompanyUserDto = ApiResponse<PublicCompanyUserDto[]>;
export type ApiResponseListScheduleDto = ApiResponse<ScheduleDto[]>;
export type ApiResponseListUserDto = ApiResponse<UserDto[]>;
export type ApiResponsePaginatedResponseAppointmentDto = ApiResponse<PaginatedResponseAppointmentDto>;
export type ApiResponsePaginatedResponseCompanyUserDto = ApiResponse<PaginatedResponseCompanyUserDto>;
export type ApiResponsePaginatedResponseContactDto = ApiResponse<PaginatedResponseContactDto>;
export type ApiResponsePaginatedResponseServiceDto = ApiResponse<PaginatedResponseServiceDto>;
export type ApiResponsePaginatedResponseServiceGroupDto = ApiResponse<PaginatedResponseServiceGroupDto>;
export type ApiResponseScheduleDto = ApiResponse<ScheduleDto>;
export type ApiResponseServiceDto = ApiResponse<ServiceDto>;
export type ApiResponseServiceGroupDto = ApiResponse<ServiceGroupDto>;
export type ApiResponseUnit = ApiResponse<void>;
export type ApiResponseUserDto = ApiResponse<UserDto>;
