import { Access, BrachCategory, type RouteBranch } from '../route-types';

export const EMBEDDED_ROUTES: RouteBranch[] = [
  {
    id: 'embed',
    href: '/embed',
    label: 'Embed',
    category: BrachCategory.PUBLIC,
    accessType: Access.PUBLIC,
    hidden: true,
    children: [
      {
        id: 'embed.booking',
        href: '/embed/booking',
        label: 'Embed Booking',
        category: BrachCategory.PUBLIC,
        accessType: Access.PUBLIC,
        hidden: true,
        children: [
          {
            id: 'embed.booking.appointment',
            href: '/embed/booking/appointment',
            category: BrachCategory.PUBLIC,
            accessType: Access.PUBLIC,
            hidden: true,
            children: [
              {
                id: 'embed.booking.appointment.session',
                href: '/embed/booking/appointment/session',
                category: BrachCategory.PUBLIC,
                accessType: Access.PUBLIC,
                hidden: true,
                children: [
                  {
                    id: 'embed.booking.appointment.session.contact',
                    href: '/embed/booking/appointment/session/contact',
                    label: 'Bruker',
                    category: BrachCategory.NONE,
                    accessType: Access.PUBLIC,
                    hidden: true,
                    children: [
                      {
                        id: 'embed.booking.appointment.session.contact.sign-in',
                        href: '/embed/booking/appointment/session/contact/sign-in',
                        category: BrachCategory.NONE,
                        accessType: Access.PUBLIC,
                        hidden: true,
                        excludeLayout: true,
                      },
                      {
                        id: 'embed.booking.appointment.session.contact.sign-up',
                        href: '/embed/booking/appointment/session/contact/sign-up',
                        category: BrachCategory.NONE,
                        accessType: Access.PUBLIC,
                        hidden: true,
                        excludeLayout: true,
                      },
                      {
                        id: 'embed.booking.appointment.session.contact.verify-email',
                        href: '/embed/booking/appointment/session/contact/verify-email',
                        category: BrachCategory.NONE,
                        accessType: Access.PUBLIC,
                        hidden: true,
                        excludeLayout: true,
                      },
                      {
                        id: 'embed.booking.appointment.session.contact.verify-mobile',
                        href: '/embed/booking/appointment/session/contact/verify-mobile',
                        category: BrachCategory.NONE,
                        accessType: Access.PUBLIC,
                        hidden: true,
                        excludeLayout: true,
                      },
                      {
                        id: 'embed.booking.appointment.session.contact.collect-email',
                        href: '/embed/booking/appointment/session/contact/collect-email',
                        category: BrachCategory.NONE,
                        accessType: Access.PUBLIC,
                        hidden: true,
                        excludeLayout: true,
                      },
                      {
                        id: 'embed.booking.appointment.session.contact.collect-mobile',
                        href: '/embed/booking/appointment/session/contact/collect-mobile',
                        category: BrachCategory.NONE,
                        accessType: Access.PUBLIC,
                        hidden: true,
                        excludeLayout: true,
                      },
                    ],
                  },
                  {
                    id: 'embed.booking.appointment.session.employee',
                    href: '/embed/booking/appointment/session/employee',
                    label: 'Velg behandler',
                    category: BrachCategory.NONE,
                    accessType: Access.PUBLIC,
                    hidden: true,
                  },
                  {
                    id: 'embed.booking.appointment.session.select-services',
                    href: '/embed/booking/appointment/session/select-services',
                    label: 'Velg tjenester',
                    category: BrachCategory.NONE,
                    accessType: Access.PUBLIC,
                    hidden: true,
                  },
                  {
                    id: 'embed.booking.appointment.session.select-time',
                    href: '/embed/booking/appointment/session/select-time',
                    label: 'Velg tidspunkt',
                    category: BrachCategory.NONE,
                    accessType: Access.PUBLIC,
                    hidden: true,
                  },
                  {
                    id: 'embed.booking.appointment.session.overview',
                    href: '/embed/booking/appointment/session/overview',
                    label: 'Oversikt',
                    category: BrachCategory.NONE,
                    accessType: Access.PUBLIC,
                    hidden: true,
                  },
                ],
              },
              {
                id: 'embed.booking.appointment.success',
                href: '/embed/booking/appointment/success',
                category: BrachCategory.NONE,
                accessType: Access.PUBLIC,
                hidden: true,
              },
              {
                id: 'embed.booking.appointment.cancel',
                href: '/embed/booking/appointment/cancel',
                category: BrachCategory.NONE,
                accessType: Access.PUBLIC,
                hidden: true,
              },
            ],
          },
          {
            id: 'embed.booking.my-appointments',
            href: '/embed/booking/my-appointments',
            label: 'Mine bookinger',
            category: BrachCategory.USER,
            accessType: Access.AUTHENTICATED,
            hidden: true,
          },
        ],
      },
    ],
  },
];
