import { Access, BrachCategory, RoutePlaceMent, UserRole, type RouteBranch } from '../route-types';

export const SYSTEM_ADMIN_ROUTES: RouteBranch[] = [
  {
      id: 'system-admin',
      href: '/system-admin',
      label: 'Systemadministrasjon',
      category: BrachCategory.USER,
      placement: RoutePlaceMent.SIDEBAR,
      accessType: Access.AUTHENTICATED,
      userRoles: [UserRole.SYSTEM_ADMIN],
      iconName: 'Settings',
      children: [
        {
          id: 'system-admin.users',
          href: '/system-admin/users',
          label: 'Brukere',
          category: BrachCategory.USER,
          accessType: Access.AUTHENTICATED,
          userRoles: [UserRole.SYSTEM_ADMIN],
          children: [
            {
              id: 'system-admin.users.invite',
              href: '/system-admin/users/invite',
              label: 'Inviter bruker',
              category: BrachCategory.USER,
              accessType: Access.AUTHENTICATED,
              userRoles: [UserRole.SYSTEM_ADMIN],
            },
            {
              id: 'system-admin.users.details',
              href: '/system-admin/users/details',
              label: 'Hent bruker',
              category: BrachCategory.USER,
              accessType: Access.AUTHENTICATED,
              userRoles: [UserRole.SYSTEM_ADMIN],
            },
          ],
        },
        {
          id: 'system-admin.companies',
          href: '/system-admin/companies',
          label: 'Selskaper',
          category: BrachCategory.USER,
          accessType: Access.AUTHENTICATED,
          userRoles: [UserRole.SYSTEM_ADMIN],
          children: [
            {
              id: 'system-admin.companies.create',
              href: '/system-admin/companies/create',
              label: 'Opprett selskap',
              category: BrachCategory.USER,
              accessType: Access.AUTHENTICATED,
              userRoles: [UserRole.SYSTEM_ADMIN],
            },
            {
              id: 'system-admin.companies.roles',
              href: '/system-admin/companies/roles',
              label: 'Tildel roller',
              category: BrachCategory.USER,
              accessType: Access.AUTHENTICATED,
              userRoles: [UserRole.SYSTEM_ADMIN],
            },
            {
              id: 'system-admin.companies.products',
              href: '/system-admin/companies/products',
              label: 'Tildel produkter',
              category: BrachCategory.USER,
              accessType: Access.AUTHENTICATED,
              userRoles: [UserRole.SYSTEM_ADMIN],
            },
          ],
        },
        {
          id: 'system-admin.diagnostics',
          href: '/system-admin/diagnostics',
          label: 'Diagnostikk',
          category: BrachCategory.USER,
          accessType: Access.AUTHENTICATED,
          userRoles: [UserRole.SYSTEM_ADMIN],
          children: [
            {
              id: 'system-admin.diagnostics.booking',
              href: '/system-admin/diagnostics/booking',
              label: 'Booking',
              category: BrachCategory.USER,
              accessType: Access.AUTHENTICATED,
              userRoles: [UserRole.SYSTEM_ADMIN],
            },
            {
              id: 'system-admin.diagnostics.booking.public-appointment-cancellation-by-token',
              href: '/system-admin/diagnostics/booking/public-appointment-cancellation-by-token',
              label: 'Public appointment cancellation by token',
              category: BrachCategory.USER,
              accessType: Access.AUTHENTICATED,
              userRoles: [UserRole.SYSTEM_ADMIN],
              hidden: true,
            },
          ],
        },
        {
          id: 'system-admin.smtp',
          href: '/system-admin/smtp',
          label: 'SMTP',
          category: BrachCategory.USER,
          accessType: Access.AUTHENTICATED,
          userRoles: [UserRole.SYSTEM_ADMIN],
          children: [
            {
              id: 'system-admin.smtp.diagnostics',
              href: '/system-admin/smtp/diagnostics',
              label: 'Diagnostikk',
              category: BrachCategory.USER,
              accessType: Access.AUTHENTICATED,
              userRoles: [UserRole.SYSTEM_ADMIN],
            },
          ],
        },
      ],
    }
];
